// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiZG-U5xaTtjMsyzvEA1v--NYpcT54IU8',
    appId: '1:137172353703:web:068d791537d78812569182',
    messagingSenderId: '137172353703',
    projectId: 'authentification-pfe-35b79',
    authDomain: 'authentification-pfe-35b79.firebaseapp.com',
    storageBucket: 'authentification-pfe-35b79.appspot.com',
    databaseURL:
        'https://authentification-pfe-35b79-default-rtdb.europe-west1.firebasedatabase.app/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2T3Sb3thZ8TvJ-EM1SQG26jF_oITgmIk',
    appId: '1:137172353703:android:76ab1960ce84eee1569182',
    messagingSenderId: '137172353703',
    projectId: 'authentification-pfe-35b79',
    storageBucket: 'authentification-pfe-35b79.appspot.com',
    databaseURL:
        'https://authentification-pfe-35b79-default-rtdb.europe-west1.firebasedatabase.app/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyR0i3D7dpktw230XBvqxjsEHwhDZAZXE',
    appId: '1:137172353703:ios:1589ac83810c663d569182',
    messagingSenderId: '137172353703',
    projectId: 'authentification-pfe-35b79',
    storageBucket: 'authentification-pfe-35b79.appspot.com',
    iosBundleId: 'com.example.smartinsole',
    databaseURL:
        'https://authentification-pfe-35b79-default-rtdb.europe-west1.firebasedatabase.app/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyR0i3D7dpktw230XBvqxjsEHwhDZAZXE',
    appId: '1:137172353703:ios:f86821049e6aecdc569182',
    messagingSenderId: '137172353703',
    projectId: 'authentification-pfe-35b79',
    storageBucket: 'authentification-pfe-35b79.appspot.com',
    iosBundleId: 'com.example.smartinsole.RunnerTests',
    databaseURL:
        'https://authentification-pfe-35b79-default-rtdb.europe-west1.firebasedatabase.app/',
  );
}
